server:
  port: 8761
spring:
  application:
    name: livegoods-eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

logging:
  pattern:
    console: '%d{MM/dd HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'