server:
  port: 9010
spring:
  application:
    name: livegoods-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yunshu-cloud/config-demo
          search-paths:
            - livegoods
      label: main

eureka:
  client:
    service-url:
      defaultZone: http://121.43.236.238:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  pattern:
    console: '%d{MM/dd HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'